version: '3.7'

services:
  app:
    container_name: gql-psql-backend
    build:
      context: ./app
      target: build
    volumes:
      - ./app:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: gwp
      DB_PASSWORD: gwp
      DB_NAME: gwp
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    tty: true

  db:
    container_name: gql-psql-db
    image: postgres:11
    volumes:
      - gql-app-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: gwp
      POSTGRES_ROOT_PASSWORD: gwp
      POSTGRES_DATABASE: gwp
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    expose:
      - 5432
    ports:
      - 5432:5432
    tty: true


volumes:
  gql-app-db: