// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

type NewDetail struct {
	UserID  int    `json:"userId"`
	TodoID  int    `json:"todo_id"`
	Content string `json:"content"`
}

type NewParent struct {
	Name string `json:"name"`
}

type NewTodo struct {
	UserID  int    `json:"userId"`
	Content string `json:"content"`
}

type NewUser struct {
	Name string `json:"name"`
}

type ParentToUser struct {
	ParentID int `json:"parentId"`
	UserID   int `json:"userId"`
}

type FixedTodo struct {
	ID      int    `json:"id"`
	Content string `json:"content"`
}
