// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

type NewTodo struct {
	Content string `json:"content"`
	UserID  int    `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}
